/* =====================================================================
 PostgreSQL DDL — 환자·건강검진·장애·통계
 ===================================================================== */

-- 환자 마스터
CREATE TABLE IF NOT EXISTS "Patient" (
    patient_no          BIGINT        NOT NULL,
    patient_name        VARCHAR(50)   NOT NULL,
    patient_rrn         VARCHAR(14)   NOT NULL,
    patient_gender      VARCHAR(10)   NOT NULL,
    patient_birth       DATE          NULL,
    patient_address     VARCHAR(200)  NULL,
    patient_email       VARCHAR(100)  NOT NULL,
    patient_tel         VARCHAR(20)   NOT NULL,
    patient_foreign     CHAR(1)       NOT NULL DEFAULT '0',
    patient_passport    VARCHAR(50)   NULL,
    patient_hypass_YN   CHAR(1)       NULL,
    patient_last_visit  DATE          NULL,
    guardian            VARCHAR(50)   NULL,
    created_date        TIMESTAMP     NULL,
    last_modified_date  TIMESTAMP     NULL,
    intt_cd             VARCHAR(10)   NULL,
    PRIMARY KEY (patient_no),
    CONSTRAINT uk_patient_rrn UNIQUE (patient_rrn),
    CONSTRAINT uk_patient_email UNIQUE (patient_email),
    CONSTRAINT uk_patient_tel UNIQUE (patient_tel),
    CONSTRAINT uk_patient_passport UNIQUE (patient_passport)
);

COMMENT ON TABLE "Patient" IS '환자 마스터';
COMMENT ON COLUMN "Patient".patient_no IS '환자번호 PK, 8자리 환자식별자';
COMMENT ON COLUMN "Patient".patient_name IS '환자명';
COMMENT ON COLUMN "Patient".patient_rrn IS '주민등록번호 암호화 저장 권장, 유일값 권장';
COMMENT ON COLUMN "Patient".patient_gender IS '성별 코드, 남성 여성 등';
COMMENT ON COLUMN "Patient".patient_birth IS '생년월일';
COMMENT ON COLUMN "Patient".patient_address IS '주소';
COMMENT ON COLUMN "Patient".patient_email IS '이메일 필드 중복 불가, 값 객체 패턴';
COMMENT ON COLUMN "Patient".patient_tel IS '연락처 필드 중복 불가, 값 객체 패턴';
COMMENT ON COLUMN "Patient".patient_foreign IS '외국인 여부, 예 아니오 또는 1과 0 코드';
COMMENT ON COLUMN "Patient".patient_passport IS '여권번호, 외국인인 경우 유일해야 함';
COMMENT ON COLUMN "Patient".patient_hypass_YN IS '하이패스 자동수납 사용 여부';
COMMENT ON COLUMN "Patient".patient_last_visit IS '최근 방문일';
COMMENT ON COLUMN "Patient".guardian IS '보호자 정보';
COMMENT ON COLUMN "Patient".created_date IS '생성일시';
COMMENT ON COLUMN "Patient".last_modified_date IS '수정일시';
COMMENT ON COLUMN "Patient".intt_cd IS '기관 코드';


/* =====================================================================
 2-1. 앱·웨어러블 사용자
 ===================================================================== */

CREATE TABLE IF NOT EXISTS user_app_profile (
    patient_no        BIGINT         NOT NULL,
    app_user_id       VARCHAR(32)    NULL,
    blood_type        VARCHAR(10)    NULL,
    height_cm         NUMERIC(5,1)   NULL,
    weight_kg         NUMERIC(5,1)   NULL,
    created_date      TIMESTAMP      NULL,
    last_modified_date TIMESTAMP     NULL,
    intt_cd           VARCHAR(10)    NULL,
    PRIMARY KEY (patient_no),
    CONSTRAINT fk_user_app_profile_patient FOREIGN KEY (patient_no) REFERENCES "Patient" (patient_no)
);

COMMENT ON TABLE user_app_profile IS '앱·기기 사용자 확장 프로필. MySQL Patient.patient_no와 1:1. 성명·성별·연락은 Patient와 동기화';
COMMENT ON COLUMN user_app_profile.patient_no IS 'MySQL·PostgreSQL 공통 환자 키, 병원–앱 연계 기준';
COMMENT ON COLUMN user_app_profile.app_user_id IS '앱/기기 화면용 사용자 ID(예: 1234)';
COMMENT ON COLUMN user_app_profile.blood_type IS '혈액형 AB 등';
COMMENT ON COLUMN user_app_profile.height_cm IS '키 cm';
COMMENT ON COLUMN user_app_profile.weight_kg IS '몸무게 kg';
COMMENT ON COLUMN user_app_profile.created_date IS '생성일시';
COMMENT ON COLUMN user_app_profile.last_modified_date IS '수정일시';
COMMENT ON COLUMN user_app_profile.intt_cd IS '기관 코드';

-- 실시간·시계열 측정 (심박·혈압·체온·스트레스 등)
CREATE TABLE IF NOT EXISTS user_vital_measurement (
    vital_id                   BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    patient_no                 BIGINT        NOT NULL,
    measured_at                TIMESTAMP     NOT NULL,
    heart_rate_bpm             INTEGER       NULL,
    blood_pressure_systolic    INTEGER       NULL,
    blood_pressure_diastolic   INTEGER       NULL,
    body_temp_c                NUMERIC(4,1)  NULL,
    stress_score               NUMERIC(6,2)  NULL,
    source_channel             VARCHAR(32)   NULL,
    synced_to_mysql_at         TIMESTAMP     NULL,
    created_date               TIMESTAMP     NULL,
    intt_cd                    VARCHAR(10)   NULL,
    PRIMARY KEY (vital_id),
    CONSTRAINT fk_user_vital_patient FOREIGN KEY (patient_no) REFERENCES "Patient" (patient_no)
);

COMMENT ON TABLE user_vital_measurement IS '실시간 상태(심박·혈압·체온·스트레스) 시계열. 환자=사용자 동일 patient_no';
COMMENT ON COLUMN user_vital_measurement.vital_id IS '측정 행 PK';
COMMENT ON COLUMN user_vital_measurement.patient_no IS 'MySQL Patient와 동일 키';
COMMENT ON COLUMN user_vital_measurement.measured_at IS '측정 시각';
COMMENT ON COLUMN user_vital_measurement.heart_rate_bpm IS '심박수';
COMMENT ON COLUMN user_vital_measurement.blood_pressure_systolic IS '수축기 혈압';
COMMENT ON COLUMN user_vital_measurement.blood_pressure_diastolic IS '이완기 혈압';
COMMENT ON COLUMN user_vital_measurement.body_temp_c IS '체온';
COMMENT ON COLUMN user_vital_measurement.stress_score IS '스트레스 지수';
COMMENT ON COLUMN user_vital_measurement.source_channel IS 'wearable / app 등';
COMMENT ON COLUMN user_vital_measurement.created_date IS '적재일시';
COMMENT ON COLUMN user_vital_measurement.intt_cd IS '기관 코드';
COMMENT ON COLUMN user_vital_measurement.synced_to_mysql_at IS 'MySQL wearable_vital 적재 완료 시각';

CREATE INDEX IF NOT EXISTS idx_uvm_patient_measured ON user_vital_measurement (patient_no, measured_at DESC);
CREATE INDEX IF NOT EXISTS idx_uvm_sync_mysql ON user_vital_measurement (synced_to_mysql_at) WHERE synced_to_mysql_at IS NULL;

-- 일 단위 목표·요약 (걸음·수면·스트레스 등 오늘의 목표 화면)
CREATE TABLE IF NOT EXISTS user_daily_wellness (
    patient_no       BIGINT        NOT NULL,
    summary_date     DATE          NOT NULL,
    step_count       INTEGER       NOT NULL DEFAULT 0,
    step_goal        INTEGER       NOT NULL DEFAULT 1000,
    sleep_hours      NUMERIC(4,1)  NULL,
    stress_level     NUMERIC(6,2)  NULL,
    synced_to_mysql_at TIMESTAMP   NULL,
    created_date     TIMESTAMP     NULL,
    last_modified_date TIMESTAMP   NULL,
    intt_cd          VARCHAR(10)   NULL,
    PRIMARY KEY (patient_no, summary_date),
    CONSTRAINT fk_user_daily_patient FOREIGN KEY (patient_no) REFERENCES "Patient" (patient_no)
);

COMMENT ON TABLE user_daily_wellness IS '일별 건강 목표·집계. 걸음 목표/달성, 수면 시간, 스트레스 요약 등';
COMMENT ON COLUMN user_daily_wellness.patient_no IS 'MySQL Patient와 동일 키';
COMMENT ON COLUMN user_daily_wellness.summary_date IS '현지 일자 기준';
COMMENT ON COLUMN user_daily_wellness.step_count IS '걸음 수';
COMMENT ON COLUMN user_daily_wellness.step_goal IS '목표 걸음';
COMMENT ON COLUMN user_daily_wellness.sleep_hours IS '수면 시간';
COMMENT ON COLUMN user_daily_wellness.stress_level IS '일 단위 스트레스 요약';
COMMENT ON COLUMN user_daily_wellness.created_date IS '생성일시';
COMMENT ON COLUMN user_daily_wellness.last_modified_date IS '수정일시';
COMMENT ON COLUMN user_daily_wellness.intt_cd IS '기관 코드';
COMMENT ON COLUMN user_daily_wellness.synced_to_mysql_at IS 'MySQL wearable_daily_wellness 적재 완료 시각';

CREATE INDEX IF NOT EXISTS idx_udw_summary_date ON user_daily_wellness (summary_date);


/* =====================================================================
 2-2. 개인 진료·검사 타임라인
 ===================================================================== */

CREATE TABLE IF NOT EXISTS patient_clinical_event (
    clinical_event_id   BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    patient_no          BIGINT        NOT NULL,
    category            VARCHAR(40)   NOT NULL,
    occurred_on         DATE          NOT NULL,
    department          VARCHAR(100)  NULL,
    title               VARCHAR(200)  NOT NULL,
    summary             TEXT          NULL,
    status              VARCHAR(30)   NULL,
    institution_name    VARCHAR(200)  NULL,
    source_mysql_treatment_id BIGINT NULL,
    created_date        TIMESTAMP     NULL,
    intt_cd             VARCHAR(10)   NULL,
    PRIMARY KEY (clinical_event_id),
    CONSTRAINT fk_pce_patient FOREIGN KEY (patient_no) REFERENCES "Patient" (patient_no)
);

COMMENT ON TABLE patient_clinical_event IS '환자별 진료·검사·처방 등 이력. category 로 유형 구분(외래·입원·응급·건검·검사 등)';
COMMENT ON COLUMN patient_clinical_event.source_mysql_treatment_id IS 'MySQL treatments.treatment_id 연계 시 중복 방지';
COMMENT ON COLUMN patient_clinical_event.category IS 'OUTPATIENT, EMERGENCY, INPATIENT, HEALTH_CHECKUP, LAB, IMAGING, PHARMACY, REHAB, TELEMEDICINE 등';
COMMENT ON COLUMN patient_clinical_event.occurred_on IS '발생일(방문·입원일·예약일 등)';
COMMENT ON COLUMN patient_clinical_event.department IS '진료과';
COMMENT ON COLUMN patient_clinical_event.title IS '한 줄 제목';
COMMENT ON COLUMN patient_clinical_event.summary IS '상세 요약';
COMMENT ON COLUMN patient_clinical_event.status IS 'COMPLETED, SCHEDULED, CANCELLED 등(저장은 영문 코드, 앱·대시보드에서 한글 표시로 변환)';
COMMENT ON COLUMN patient_clinical_event.institution_name IS '기관명';

CREATE INDEX IF NOT EXISTS idx_pce_patient_occurred ON patient_clinical_event (patient_no, occurred_on DESC);
CREATE INDEX IF NOT EXISTS idx_pce_patient_category ON patient_clinical_event (patient_no, category);
CREATE UNIQUE INDEX IF NOT EXISTS uk_pce_mysql_treatment_id ON patient_clinical_event (source_mysql_treatment_id);


/* =====================================================================
 2-3. ETL 런타임 상태
 ===================================================================== */

CREATE TABLE IF NOT EXISTS etl_runtime_state (
    job_code    VARCHAR(64)   NOT NULL,
    cursor_value BIGINT       NOT NULL DEFAULT 0,
    meta        JSONB         NULL,
    updated_at  TIMESTAMP     NULL,
    PRIMARY KEY (job_code)
);

COMMENT ON TABLE etl_runtime_state IS '스케줄러 전용 커서 (예: wearables 다음 환자 인덱스)';
COMMENT ON COLUMN etl_runtime_state.job_code IS '예: wearable_round_robin';
COMMENT ON COLUMN etl_runtime_state.cursor_value IS '정수 커서';
COMMENT ON COLUMN etl_runtime_state.meta IS '선택 JSON';


/* =====================================================================
 7. 건강검진·장애 관련 영역, 지원 패키지
 ===================================================================== */

-- 건강검진 기관 전국 건강검진 가능 의료기관 목록
CREATE TABLE IF NOT EXISTS health_checkup_institution (
    institution_id       BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    region_code          VARCHAR(10)  NULL,
    region_name          VARCHAR(50)  NULL,
    institution_name     VARCHAR(200) NOT NULL,
    institution_type     VARCHAR(50)  NOT NULL,
    address              VARCHAR(500) NOT NULL,
    sido                 VARCHAR(50)  NULL,
    sigungu              VARCHAR(50)  NULL,
    latitude             DOUBLE PRECISION NULL,
    longitude            DOUBLE PRECISION NULL,
    phone_number         VARCHAR(20)  NULL,
    is_active            SMALLINT     NOT NULL DEFAULT 1,
    data_source          VARCHAR(100) NULL,
    data_date            DATE         NULL,
    created_date         TIMESTAMP    NULL,
    last_modified_date   TIMESTAMP    NULL,
    intt_cd              VARCHAR(10)  NULL,
    PRIMARY KEY (institution_id)
);

COMMENT ON TABLE health_checkup_institution IS '건강검진 가능 기관 마스터';
COMMENT ON COLUMN health_checkup_institution.institution_id IS '검진 기관 PK';
COMMENT ON COLUMN health_checkup_institution.region_code IS '지역 코드';
COMMENT ON COLUMN health_checkup_institution.region_name IS '지역명';
COMMENT ON COLUMN health_checkup_institution.institution_name IS '기관명';
COMMENT ON COLUMN health_checkup_institution.institution_type IS '기관 유형 병원/의원/검진센터 등';
COMMENT ON COLUMN health_checkup_institution.address IS '주소';
COMMENT ON COLUMN health_checkup_institution.sido IS '시도';
COMMENT ON COLUMN health_checkup_institution.sigungu IS '시군구';
COMMENT ON COLUMN health_checkup_institution.latitude IS '위도';
COMMENT ON COLUMN health_checkup_institution.longitude IS '경도';
COMMENT ON COLUMN health_checkup_institution.phone_number IS '대표 전화번호';
COMMENT ON COLUMN health_checkup_institution.is_active IS '활성 여부 1/0';
COMMENT ON COLUMN health_checkup_institution.data_source IS '데이터 출처 공공데이터 포털 등';
COMMENT ON COLUMN health_checkup_institution.data_date IS '데이터 기준일';
COMMENT ON COLUMN health_checkup_institution.created_date IS '생성일시';
COMMENT ON COLUMN health_checkup_institution.last_modified_date IS '수정일시';
COMMENT ON COLUMN health_checkup_institution.intt_cd IS '기관 코드';

CREATE INDEX IF NOT EXISTS idx_hci_region_code ON health_checkup_institution (region_code);
CREATE INDEX IF NOT EXISTS idx_hci_institution_type ON health_checkup_institution (institution_type);
CREATE INDEX IF NOT EXISTS idx_hci_institution_name ON health_checkup_institution (institution_name);
CREATE INDEX IF NOT EXISTS idx_hci_is_active ON health_checkup_institution (is_active);
CREATE INDEX IF NOT EXISTS idx_hci_region_type ON health_checkup_institution (region_code, institution_type);

-- 환자 장애 정보
CREATE TABLE IF NOT EXISTS disability (
    disability_id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    patient_no             BIGINT       NOT NULL,
    disability_grade       VARCHAR(10)  NOT NULL,
    disability_type        VARCHAR(50)  NULL,
    assistive_device_YN    CHAR(1)      NOT NULL,
    disability_device_type VARCHAR(100) NULL,
    created_date           TIMESTAMP    NULL,
    last_modified_date     TIMESTAMP    NULL,
    intt_cd                VARCHAR(10)  NULL,
    PRIMARY KEY (disability_id),
    CONSTRAINT uk_disability_patient UNIQUE (patient_no),
    CONSTRAINT fk_disability_patient FOREIGN KEY (patient_no) REFERENCES "Patient" (patient_no)
);

COMMENT ON TABLE disability IS '환자 장애 정보';
COMMENT ON COLUMN disability.disability_id IS '장애 정보 PK';
COMMENT ON COLUMN disability.patient_no IS '환자번호, Patient 참조, 환자당 하나';
COMMENT ON COLUMN disability.disability_grade IS '장애 등급 1급 ~ 6급';
COMMENT ON COLUMN disability.disability_type IS '장애 유형 지체/시각/청각 등';
COMMENT ON COLUMN disability.assistive_device_YN IS '보조기구 필요 여부, 예 아니오 코드';
COMMENT ON COLUMN disability.disability_device_type IS '보조기구 종류 휠체어/보청기 등';
COMMENT ON COLUMN disability.created_date IS '생성일시';
COMMENT ON COLUMN disability.last_modified_date IS '수정일시';
COMMENT ON COLUMN disability.intt_cd IS '기관 코드';

-- 장애인 돌봄/지원 기관
CREATE TABLE IF NOT EXISTS disability_care_institution (
    institution_id     BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    institution_type   VARCHAR(20)  NOT NULL,
    institution_name   VARCHAR(200) NOT NULL,
    service_type       VARCHAR(50)  NOT NULL,
    address            VARCHAR(500) NOT NULL,
    sido               VARCHAR(50)  NULL,
    sigungu            VARCHAR(50)  NULL,
    latitude           DOUBLE PRECISION NULL,
    longitude          DOUBLE PRECISION NULL,
    is_active          SMALLINT     NOT NULL DEFAULT 1,
    created_date       TIMESTAMP    NULL,
    last_modified_date TIMESTAMP    NULL,
    intt_cd            VARCHAR(10)  NULL,
    PRIMARY KEY (institution_id)
);

COMMENT ON TABLE disability_care_institution IS '장애인 돌봄/지원 기관';
COMMENT ON COLUMN disability_care_institution.institution_id IS '돌봄 기관 PK';
COMMENT ON COLUMN disability_care_institution.institution_type IS '기관 분류';
COMMENT ON COLUMN disability_care_institution.institution_name IS '기관명';
COMMENT ON COLUMN disability_care_institution.service_type IS '서비스 유형 활동지원/재활/주간보호 등';
COMMENT ON COLUMN disability_care_institution.address IS '주소';
COMMENT ON COLUMN disability_care_institution.sido IS '시도';
COMMENT ON COLUMN disability_care_institution.sigungu IS '시군구';
COMMENT ON COLUMN disability_care_institution.latitude IS '위도';
COMMENT ON COLUMN disability_care_institution.longitude IS '경도';
COMMENT ON COLUMN disability_care_institution.is_active IS '활성 여부 1/0';
COMMENT ON COLUMN disability_care_institution.created_date IS '생성일시';
COMMENT ON COLUMN disability_care_institution.last_modified_date IS '수정일시';
COMMENT ON COLUMN disability_care_institution.intt_cd IS '기관 코드';

CREATE INDEX IF NOT EXISTS idx_dci_service_type ON disability_care_institution (service_type);
CREATE INDEX IF NOT EXISTS idx_dci_sido ON disability_care_institution (sido);
CREATE INDEX IF NOT EXISTS idx_dci_institution_type ON disability_care_institution (institution_type);
CREATE INDEX IF NOT EXISTS idx_dci_is_active ON disability_care_institution (is_active);


/* =====================================================================
 8. 건강관련 통계 영역, 임상에서 분석 도구로 이어지는 집계
 ===================================================================== */

-- 입원 진료 통계 연도/지역/기관유형별 집계
CREATE TABLE IF NOT EXISTS inpatient_statistics (
    statistics_id      BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    statistics_year    VARCHAR(4)   NOT NULL,
    institution_type   VARCHAR(50)  NOT NULL,
    region_code        VARCHAR(10)  NULL,
    region_name        VARCHAR(50)  NULL,
    visit_days         BIGINT       NOT NULL DEFAULT 0,
    benefit_days       BIGINT       NOT NULL DEFAULT 0,
    medical_fee        BIGINT       NOT NULL DEFAULT 0,
    benefit_fee        BIGINT       NOT NULL DEFAULT 0,
    data_source        VARCHAR(100) NULL,
    data_date          DATE         NULL,
    created_date       TIMESTAMP    NULL,
    last_modified_date TIMESTAMP    NULL,
    intt_cd            VARCHAR(10)  NULL,
    PRIMARY KEY (statistics_id)
);

COMMENT ON TABLE inpatient_statistics IS '입원 진료 통계';
COMMENT ON COLUMN inpatient_statistics.statistics_id IS '통계 PK';
COMMENT ON COLUMN inpatient_statistics.statistics_year IS '통계 연도 예: 2024';
COMMENT ON COLUMN inpatient_statistics.institution_type IS '의료기관 유형 상급/종합/병원/의원 등';
COMMENT ON COLUMN inpatient_statistics.region_code IS '지역 코드';
COMMENT ON COLUMN inpatient_statistics.region_name IS '지역명';
COMMENT ON COLUMN inpatient_statistics.visit_days IS '내원 일수';
COMMENT ON COLUMN inpatient_statistics.benefit_days IS '급여 일수';
COMMENT ON COLUMN inpatient_statistics.medical_fee IS '진료비 총액 원';
COMMENT ON COLUMN inpatient_statistics.benefit_fee IS '급여비 총액 원';
COMMENT ON COLUMN inpatient_statistics.data_source IS '데이터 출처';
COMMENT ON COLUMN inpatient_statistics.data_date IS '데이터 기준일';
COMMENT ON COLUMN inpatient_statistics.created_date IS '생성일시';
COMMENT ON COLUMN inpatient_statistics.last_modified_date IS '수정일시';
COMMENT ON COLUMN inpatient_statistics.intt_cd IS '기관 코드';

CREATE INDEX IF NOT EXISTS idx_ips_statistics_year ON inpatient_statistics (statistics_year);
CREATE INDEX IF NOT EXISTS idx_ips_institution_type ON inpatient_statistics (institution_type);
CREATE INDEX IF NOT EXISTS idx_ips_region_code ON inpatient_statistics (region_code);
CREATE INDEX IF NOT EXISTS idx_ips_year_region ON inpatient_statistics (statistics_year, region_code);

-- 진료과별 진료 통계
CREATE TABLE IF NOT EXISTS treatment_department_statistics (
    statistics_id      BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    statistics_year    VARCHAR(4)   NOT NULL,
    region_code        VARCHAR(10)  NULL,
    region_name        VARCHAR(50)  NULL,
    department_name    VARCHAR(100) NOT NULL,
    patient_count      BIGINT       NOT NULL DEFAULT 0,
    treatment_count    BIGINT       NOT NULL DEFAULT 0,
    medical_fee        BIGINT       NOT NULL DEFAULT 0,
    benefit_fee        BIGINT       NOT NULL DEFAULT 0,
    data_source        VARCHAR(100) NULL,
    data_date          DATE         NULL,
    created_date       TIMESTAMP    NULL,
    last_modified_date TIMESTAMP    NULL,
    intt_cd            VARCHAR(10)  NULL,
    PRIMARY KEY (statistics_id),
    CONSTRAINT uk_tds_year_region_department UNIQUE (statistics_year, region_code, department_name)
);

COMMENT ON TABLE treatment_department_statistics IS '진료과목별 진료 통계';
COMMENT ON COLUMN treatment_department_statistics.statistics_id IS '통계 PK';
COMMENT ON COLUMN treatment_department_statistics.statistics_year IS '통계 연도';
COMMENT ON COLUMN treatment_department_statistics.region_code IS '지역 코드';
COMMENT ON COLUMN treatment_department_statistics.region_name IS '지역명';
COMMENT ON COLUMN treatment_department_statistics.department_name IS '진료과명';
COMMENT ON COLUMN treatment_department_statistics.patient_count IS '환자 수';
COMMENT ON COLUMN treatment_department_statistics.treatment_count IS '진료 건수';
COMMENT ON COLUMN treatment_department_statistics.medical_fee IS '진료비 총액 원';
COMMENT ON COLUMN treatment_department_statistics.benefit_fee IS '급여비 총액 원';
COMMENT ON COLUMN treatment_department_statistics.data_source IS '데이터 출처';
COMMENT ON COLUMN treatment_department_statistics.data_date IS '데이터 기준일';
COMMENT ON COLUMN treatment_department_statistics.created_date IS '생성일시';
COMMENT ON COLUMN treatment_department_statistics.last_modified_date IS '수정일시';
COMMENT ON COLUMN treatment_department_statistics.intt_cd IS '기관 코드';

CREATE INDEX IF NOT EXISTS idx_tds_statistics_year ON treatment_department_statistics (statistics_year);
CREATE INDEX IF NOT EXISTS idx_tds_department_name ON treatment_department_statistics (department_name);
CREATE INDEX IF NOT EXISTS idx_tds_region_code ON treatment_department_statistics (region_code);
CREATE INDEX IF NOT EXISTS idx_tds_year_department ON treatment_department_statistics (statistics_year, department_name);
CREATE INDEX IF NOT EXISTS idx_tds_year_region ON treatment_department_statistics (statistics_year, region_code);
